#!/bin/bash

# install JupyterLab extension
jupyter labextension install @jupyterlab/latex
mkdir -p /etc/jupyter
echo "\
# c.LatexConfig.shell_escape = 'allow'\
\n\
c.LatexConfig.run_times = 1\
\n\
c.LatexConfig.manual_cmd_args = [\
    '/usr/local/bin/compile-latex.sh',\
    '{filename}.tex'\
]\n\
" > /etc/jupyter/jupyter_server_config.py

cp /etc/jupyter/jupyter_server_config.py /home/user/.jupyter/
mkdir -p /home/user/.sage/jupyter-4.1
cp /etc/jupyter/jupyter_server_config.py /home/user/.sage/jupyter-4.1/
