channels:
    - conda-forge
dependencies:
    - sage
    - python
    - setuptools
    - jupyterlab
    - jupyterlab-latex
    - jupyterlab-lsp
    - texlab
    - tectonic
    - chktex
    - python-lsp-server
    - pip:
        - "httpx[cli]"
        - jupyter-offlinenotebook
